// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "galigaribaldi (Galileo Cabrera Garibaldi)",
            "email": "galigaribaldi0@gmail.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/estacion": {
            "get": {
                "description": "Obtener datos a través de los siguientes parámetros: Numero de Linea (linea_id), color en español(color_esp), color en inglés(color_eng)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Estacion"
                ],
                "summary": "Datos de Estacion",
                "parameters": [
                    {
                        "type": "string",
                        "format": "nombre",
                        "description": "Search by nombre",
                        "name": "nombre",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "format": "anio",
                        "description": "Search by anio",
                        "name": "anio",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "format": "color_en",
                        "description": "Search by Color Ingles",
                        "name": "color_en",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Estacion"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    }
                }
            }
        },
        "/linea": {
            "get": {
                "description": "Obtener datos a través de los siguientes parámetros: Numero de Linea (linea_id), color en español(color_esp), color en inglés(color_eng)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Linea"
                ],
                "summary": "Datos de Linea",
                "parameters": [
                    {
                        "type": "string",
                        "format": "linea_id",
                        "description": "Search by linea_id",
                        "name": "linea_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "format": "color_esp",
                        "description": "Search by Color Español",
                        "name": "color_esp",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "format": "color_eng",
                        "description": "Search by Color Ingles",
                        "name": "color_eng",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Linea"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "httputil.HTTPError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 400
                },
                "message": {
                    "type": "string",
                    "example": "status bad request"
                }
            }
        },
        "models.DescripcionLinea": {
            "type": "object",
            "properties": {
                "anio_fin_ampliacion": {
                    "type": "integer"
                },
                "anio_inicio_ampliacion": {
                    "type": "integer"
                },
                "descripcion": {
                    "type": "string"
                },
                "descripcion_linea_id": {
                    "type": "integer"
                },
                "direccion": {
                    "type": "string"
                },
                "inicio_original": {
                    "type": "string"
                },
                "linea_base": {
                    "type": "integer"
                },
                "terminal_original": {
                    "type": "string"
                },
                "tipo_linea": {
                    "type": "string"
                }
            }
        },
        "models.Estacion": {
            "type": "object",
            "properties": {
                "alcaldia_municipio": {
                    "type": "string"
                },
                "anio": {
                    "type": "string"
                },
                "cve_est": {
                    "type": "string"
                },
                "estacion_id": {
                    "type": "integer"
                },
                "estacion_id_oficial": {
                    "type": "integer"
                },
                "estado_ciudad": {
                    "type": "string"
                },
                "existe": {
                    "type": "boolean"
                },
                "latitud": {
                    "type": "number"
                },
                "linea_id": {
                    "type": "integer"
                },
                "longitud": {
                    "type": "number"
                },
                "nombre": {
                    "type": "string"
                },
                "num_estacion": {
                    "type": "integer"
                },
                "sistema": {
                    "type": "string"
                },
                "tipo": {
                    "type": "string"
                }
            }
        },
        "models.Linea": {
            "type": "object",
            "properties": {
                "anio_inauguracion": {
                    "type": "integer"
                },
                "color_en": {
                    "type": "string"
                },
                "color_esp": {
                    "type": "string"
                },
                "descripcion_linea": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.DescripcionLinea"
                    }
                },
                "existe": {
                    "type": "boolean"
                },
                "linea_base_ramal": {
                    "type": "integer"
                },
                "linea_id": {
                    "type": "integer"
                },
                "nombre": {
                    "type": "string"
                },
                "ramal_id": {
                    "type": "integer"
                },
                "sistema": {
                    "type": "string"
                },
                "tam_km": {
                    "type": "number"
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        }
    },
    "externalDocs": {
        "description": "Github",
        "url": "https://github.com/galigaribaldi/Apimetro"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/stc",
	Schemes:          []string{},
	Title:            "Apimetro",
	Description:      "API sobre el Sistema de Transporte Colectivo (STC) de la Ciudad de México",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
