basePath: /stc
definitions:
  models.DescripcionLinea:
    properties:
      anio_fin_ampliacion:
        type: integer
      anio_inicio_ampliacion:
        type: integer
      descripcion:
        type: string
      descripcion_linea_id:
        type: integer
      direccion:
        type: string
      inicio_original:
        type: string
      linea_base:
        type: integer
      terminal_original:
        type: string
      tipo_linea:
        type: string
    type: object
  models.Linea:
    properties:
      anio_inauguracion:
        type: integer
      color_en:
        type: string
      color_esp:
        type: string
      descripcion_linea:
        items:
          $ref: '#/definitions/models.DescripcionLinea'
        type: array
      existe:
        type: boolean
      linea_base_ramal:
        type: integer
      linea_id:
        type: integer
      nombre:
        type: string
      ramal_id:
        type: integer
      sistema:
        type: string
      tam_km:
        type: number
    type: object
externalDocs:
  description: Github
  url: https://github.com/galigaribaldi/Apimetro
host: localhost:8080
info:
  contact:
    email: galigaribaldi0@gmail.com
    name: galigaribaldi (Galileo Cabrera Garibaldi)
  description: API sobre el Sistema de Transporte Colectivo (STC) de la Ciudad de
    México
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Apimetro
  version: "1.0"
paths:
  /accounts/{id}:
    get:
      consumes:
      - application/json
      description: get string by ID
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Linea'
      summary: Show an account
      tags:
      - accounts
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
