basePath: /stc
definitions:
  httputil.HTTPError:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: status bad request
        type: string
    type: object
  models.DescripcionLinea:
    properties:
      anio_fin_ampliacion:
        type: integer
      anio_inicio_ampliacion:
        type: integer
      descripcion:
        type: string
      descripcion_linea_id:
        type: integer
      direccion:
        type: string
      inicio_original:
        type: string
      linea_base:
        type: integer
      terminal_original:
        type: string
      tipo_linea:
        type: string
    type: object
  models.Estacion:
    properties:
      alcaldia_municipio:
        type: string
      anio:
        type: string
      cve_est:
        type: string
      estacion_id:
        type: integer
      estacion_id_oficial:
        type: integer
      estado_ciudad:
        type: string
      existe:
        type: boolean
      latitud:
        type: number
      linea_id:
        type: integer
      longitud:
        type: number
      nombre:
        type: string
      num_estacion:
        type: integer
      sistema:
        type: string
      tipo:
        type: string
    type: object
  models.Linea:
    properties:
      anio_inauguracion:
        type: integer
      color_en:
        type: string
      color_esp:
        type: string
      descripcion_linea:
        items:
          $ref: '#/definitions/models.DescripcionLinea'
        type: array
      existe:
        type: boolean
      linea_base_ramal:
        type: integer
      linea_id:
        type: integer
      nombre:
        type: string
      ramal_id:
        type: integer
      sistema:
        type: string
      tam_km:
        type: number
    type: object
externalDocs:
  description: Github
  url: https://github.com/galigaribaldi/Apimetro
host: localhost:8080
info:
  contact:
    email: galigaribaldi0@gmail.com
    name: galigaribaldi (Galileo Cabrera Garibaldi)
  description: API sobre el Sistema de Transporte Colectivo (STC) de la Ciudad de
    México
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Apimetro
  version: "1.0"
paths:
  /estacion:
    get:
      consumes:
      - application/json
      description: 'Obtener datos a través de los siguientes parámetros: Numero de
        Linea (linea_id), color en español(color_esp), color en inglés(color_eng)'
      parameters:
      - description: Search by nombre
        format: nombre
        in: query
        name: nombre
        type: string
      - description: Search by anio
        format: anio
        in: query
        name: anio
        type: string
      - description: Search by Color Ingles
        format: color_en
        in: query
        name: color_en
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Estacion'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Datos de Estacion
      tags:
      - Estacion
  /linea:
    get:
      consumes:
      - application/json
      description: 'Obtener datos a través de los siguientes parámetros: Numero de
        Linea (linea_id), color en español(color_esp), color en inglés(color_eng)'
      parameters:
      - description: Search by linea_id
        format: linea_id
        in: query
        name: linea_id
        type: string
      - description: Search by Color Español
        format: color_esp
        in: query
        name: color_esp
        type: string
      - description: Search by Color Ingles
        format: color_eng
        in: query
        name: color_eng
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Linea'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Datos de Linea
      tags:
      - Linea
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
